### ISSUE TITLE
Cannot Locate genotypes_to_keep.txt or phenotypes_to_keep.txt files in the repository

### ISSUE THREAD

**Issue by sciencety** [amkusmec/NAM_phenotypic_plasticity#1]
Hi, I Cannot Locate genotypes_to_keep.txt or phenotypes_to_keep.txt files in the repository. Can you please direct me to them to have a look?

**Comment by amkusmec** [comment]
I've updated the repository with those two files in the `data/` directory. They will allow you to generate the same trait matrix used in the paper.
